version: '3.9'

services:
  development:
    image: tianon/true
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      selenium:
        condition: service_started

  postgres:
    image: postgres:16.3
    container_name: docker_on_rails_test_postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ../log:/root/log:cached
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USERNAME=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.5
    container_name: docker_on_rails_test_redis
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: docker_on_rails_test_chrome
    ports:
      - 4444:4444

volumes:
  postgres:
    name: docker_on_rails_test_volume_postgres
  redis:
    name: docker_on_rails_test_volume_redis
